version: '3.8'

services:
  app:
    image: cats_gif_everywhere_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_BASE_URL=http://127.0.0.1:8081
    command: npm run dev